# compose.yaml
services:
  app:
    image: alpine
    command: sh -c "while true; do echo hello from app; sleep 2; done"
    depends_on:
      - collector
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "demo-app"

  collector:
    image: python:3.12-alpine
    ports:
      - "5514:5514/udp"
      - "8000:8000"
    volumes:
      - ./collector.py:/collector.py
    command: sh -c "pip install prometheus_client -q && python3 /collector.py"

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml
    command: -config.file=/etc/loki/config.yml

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - collector

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
